# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0fmy.grpc.service\"\x1b\n\x0bRequestUser\x12\x0c\n\x04name\x18\x01 \x01(\t\"M\n\x0cUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x32\xa8\x01\n\tMyService\x12N\n\x0fGetUserResponse\x12\x1c.my.grpc.service.RequestUser\x1a\x1d.my.grpc.service.UserResponse\x12K\n\nStreamData\x12\x1c.my.grpc.service.RequestUser\x1a\x1d.my.grpc.service.UserResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTUSER']._serialized_start=34
  _globals['_REQUESTUSER']._serialized_end=61
  _globals['_USERRESPONSE']._serialized_start=63
  _globals['_USERRESPONSE']._serialized_end=140
  _globals['_MYSERVICE']._serialized_start=143
  _globals['_MYSERVICE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
